### PR TITLE
CMake improvements and PKG-Config Integration

### LINKED ISSUE #11: Feature Request: Make Install Target, Pkgconfig, and Switch to En-/Disable Building Tests
It would be nice if the CMakeLists.txt configured an install target (to move the built libs to e.g. /usr/local/lib on Linux), as well as a package-config file to point to the installed libraries and the include directory.

Moreover, it would be nice if there was a CMake flag for disabling/enabling compilation of the test targets.

I'll create a prototype version and then open a PR.

### PR DESCRIPTION
**Pull request by BLuedtke**
Closes #11 

CMakeLists.txt now provides an install target. This installs the dynamic and static library, as well as the include headers. These are installed according to the system defaults. On Linux, this is /usr/local/lib and /usr/local/include respectively. Furthermore, a pkg-config (.pc) is installed for each library version respectively. This makes the libraries easily includable from other CMakeLists.txt.

The above functionality was added in the first commit. The most changes in CMakeLists.txt in the second commit are simply formatting.

I have not been able to test this on a Mac. Not sure what the default paths are there, but should work nonetheless.

### CODE REVIEW

**Comment by BLuedtke** [comment]
~~Ah, tests for bidib_static are not running fully. Let me fix that first.~~

 - edit: passing now, misconfig on my part

**Comment by eyip002** [comment]
- Has this been tested on one of the SWTbahn platforms?
- Does relevant portions of the README file need to be updated?

**Comment by BLuedtke** [comment]
Thank you for making the macOS adjustments.

> Has this been tested on one of the SWTbahn platforms?

Good point - not yet. No change to actual source so should run the same, but definitely better to make sure that the CMake version on the raspberri's is new enough. I'll do that once I'm healthy again.

> Does relevant portions of the README file need to be updated?

A little bit, I guess. I'll do so once I've tested how it works on the Pi's

**Comment by BLuedtke** [comment]
Thinking about the CMake Setup - If we provide an install target, it's probably a good idea to also provide an uninstall target. These are a little more complicated to setup, but I shall have a look at how it can be done here.

**Comment by eyip002** [comment]
Tested on SWTbahn Standard

**Pull request merged**
